<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <title>EChat - Bate Bapo com PHP & Ajax</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" />

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="assets/js/jquery.js" defer></script>
    <script src="assets/js/bootstrap.js" defer></script>
    <script src="assets/js/moment.js" defer></script>
    <script src="assets/js/chat.js" defer></script>
</head>
<body style="font-family:Verdana">

    <div class="container">

        <div class="row " style="padding-top:30px;">

            <div class="jumbotron">
                <h3>Seja bem vindo</h3>
                <small>Este é o projeto final do curso PHP Volume 2 - Um chat desenvolvido com PHP Orientado a Objetos, Ajax, jQuery e MySQL.</small>

            </div>
