<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <title>BOOTSTRAP CHAT EXAMPLE</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
    <link href="assets/css/style.css" rel="stylesheet" />

</head>
<body style="font-family:Verdana">

    <div class="container">

        <div class="row " style="padding-top:30px;">

            <div class="jumbotron">
                <h1>Seja bem vindo</h1>
                <p>Este é o projeto final do curso PHP Volume 2 - Um chat desenvolvido com PHP Orientado a Objetos, Ajax, jQuery e MySQL.</p>
                <?php echo EChat\Helpers\URL\GETURL::getInstance()->doAction('login', ['init_user' => true])?>
            </div>
