<div class="col-md-8">
    <div class="panel panel-info">
        <div class="panel-heading">
            Conversas
        </div>
        <div class="panel-body conversation-history">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
                <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
                <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
                <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">.asdasd..</div>
                <div role="tabpanel" class="tab-pane" id="profile">..asas.</div>
                <div role="tabpanel" class="tab-pane" id="messages">.dasda..</div>
                <div role="tabpanel" class="tab-pane" id="settings">.sdasd..</div>
            </div>
            <ul class="media-list">
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle " src="assets/img/user.png" />
                            </a>
                            <div class="media-body" >
                                Donec sit amet ligula enim. Duis vel condimentum massa.

                                Donec sit amet ligula enim. Duis vel condimentum massa.Donec sit amet ligula enim.
                                Duis vel condimentum massa.
                                Donec sit amet ligula enim. Duis vel condimentum massa.
                                <br />
                                <small class="text-muted">Alex Deo | 23rd June at 5:00pm</small>
                                <hr />
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle " src="assets/img/user.gif" />
                            </a>
                            <div class="media-body" >
                                Donec sit amet ligula enim. Duis vel condimentum massa.

                                Donec sit amet ligula enim. Duis vel condimentum massa.Donec sit amet ligula enim.
                                Duis vel condimentum massa.
                                Donec sit amet ligula enim. Duis vel condimentum massa.
                                <br />
                                <small class="text-muted">Jhon Rexa | 23rd June at 5:00pm</small>
                                <hr />
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle " src="assets/img/user.png" />
                            </a>
                            <div class="media-body" >
                                Donec sit amet ligula enim. Duis vel condimentum massa.

                                Donec sit amet ligula enim. Duis vel condimentum massa.Donec sit amet ligula enim.
                                Duis vel condimentum massa.
                                Donec sit amet ligula enim. Duis vel condimentum massa.
                                <br />
                                <small class="text-muted">Alex Deo | 23rd June at 5:00pm</small>
                                <hr />
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle " src="assets/img/user.gif" />
                            </a>
                            <div class="media-body" >
                                Donec sit amet ligula enim. Duis vel condimentum massa.

                                Donec sit amet ligula enim. Duis vel condimentum massa.Donec sit amet ligula enim.
                                Duis vel condimentum massa.
                                Donec sit amet ligula enim. Duis vel condimentum massa.
                                <br />
                                <small class="text-muted">Jhon Rexa | 23rd June at 5:00pm</small>
                                <hr />
                            </div>
                        </div>

                    </div>
                </li>
            </ul>
        </div>
        <div class="panel-footer">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Enter Message" />
                                    <span class="input-group-btn">
                                        <button class="btn btn-info" type="button">Enviar</button>
                                    </span>
            </div>
        </div>
    </div>
</div>