<div class="col-md-4">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Usuários Online
        </div>
        <div class="panel-body online-users">
            <ul class="media-list">
                <?php if ( is_array($this->template->users) ) : foreach($this->template->users as $user) : ?>
                    <li class="media">
                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle" style="max-height:40px;" src="<?php echo $this->template->gravatar->avatar($user['email']);?>" />
                                </a>
                                <div class="media-body" >
                                    <h5><a href="#" class="new-private-chat" data-hash="<?= $user['user_hash'] ?>"><?= $user['name']; ?></a></h5>
                                    <small class="text-muted">
                                        Online à
                                        <?php
                                            $curr_date = new DateTime();
                                            $lastActivity = new DateTime($user['entered_at']);
                                            $date_diff = $curr_date->diff($lastActivity);
                                            echo $date_diff->h . 'h ' . $date_diff->i . 'm ' . $date_diff->s . 's';
                                        ?>
                                    </small>
                                </div>
                            </div>

                        </div>
                    </li>
                <?php endforeach; endif; ?>

            </ul>
        </div>
    </div>

</div>