<div class="col-md-4">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Usuários Online
        </div>
        <div class="panel-body online-users">
            <ul class="media-list">

                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" style="max-height:40px;" src="assets/img/user.png" />
                            </a>
                            <div class="media-body" >
                                <h5>Alex Deo | User </h5>

                                <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" style="max-height:40px;" src="assets/img/user.gif" />
                            </a>
                            <div class="media-body" >
                                <h5>Jhon Rexa | User </h5>

                                <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" style="max-height:40px;" src="assets/img/user.png" />
                            </a>
                            <div class="media-body" >
                                <h5>Alex Deo | User </h5>

                                <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" style="max-height:40px;" src="assets/img/user.gif" />
                            </a>
                            <div class="media-body" >
                                <h5>Jhon Rexa | User </h5>

                                <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" style="max-height:40px;" src="assets/img/user.png" />
                            </a>
                            <div class="media-body" >
                                <h5>Alex Deo | User </h5>

                                <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" style="max-height:40px;" src="assets/img/user.gif" />
                            </a>
                            <div class="media-body" >
                                <h5>Jhon Rexa | User </h5>

                                <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" style="max-height:40px;" src="assets/img/user.png" />
                            </a>
                            <div class="media-body" >
                                <h5>Alex Deo | User </h5>

                                <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>

                    </div>
                </li>
                <li class="media">

                    <div class="media-body">

                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" style="max-height:40px;" src="assets/img/user.gif" />
                            </a>
                            <div class="media-body" >
                                <h5>Jhon Rexa | User </h5>

                                <small class="text-muted">Active From 3 hours</small>
                            </div>
                        </div>

                    </div>
                </li>
            </ul>
        </div>
    </div>

</div>