
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Entrar no EChat</title>

    <link href="assets/css/bootstrap.css" rel="stylesheet">

    <link href="assets/css/login.css" rel="stylesheet">

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="container">

    <form class="form-signin" method="POST" action="<?= $this->UrlBuilder()->doAction('login', ['init_user' => true]); ?>">
        <h2 class="form-signin-heading">Prencha seus dados</h2>
        <label for="inputPassword" class="sr-only">Nickname: </label>
        <input type="text" id="inputNickName" class="form-control" name="nickname" placeholder="Nickname" required>
        <label for="inputEmail" class="sr-only">E-mail</label>
        <input type="email" id="inputEmail" class="form-control" name="email" placeholder="Endereço de e-mail" required autofocus>

         <br />
        <button class="btn btn-lg btn-primary btn-block" type="submit">Bater Papo!</button>
    </form>

</div> <!-- /container -->

</body>
</html>
